stages:
  data_ingestion:
    cmd: PYTHONPATH=. python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
      - params.yaml
    outs:
      - data/raw/iris.csv

  data_preprocessing:
    cmd: PYTHONPATH=. python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - data/raw/iris.csv
      - params.yaml
    outs:
      - data/processed/iris_clean.csv

  feature_engineering:
    cmd: PYTHONPATH=. python src/feature_engineering.py
    deps:
      - src/feature_engineering.py
      - data/processed/iris_clean.csv
      - params.yaml
    outs:
      - data/features/iris_features.csv

  train:
    cmd: PYTHONPATH=. python src/train.py
    deps:
      - src/train.py
      - data/features/iris_features.csv
      - params.yaml
    outs:
      - models/model.pkl
      - metrics/preds.csv

  evaluate:
    cmd: PYTHONPATH=. python src/eval.py
    deps:
      - src/eval.py
      - metrics/preds.csv
      - params.yaml
    outs:
      - metrics/score.txt

